spring.application.name=notes
server.port=8082


spring.data.mongodb.uri=mongodb://localhost:27017/notes

spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET}
jwt.issuer=myletters-auth
jwt.audience=myletters

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
